# Generated by cpp4r: do not edit by hand

later_dll_api_version <- function() {
	.Call(`_latertest_later_dll_api_version`)
}

later_h_api_version <- function() {
	.Call(`_latertest_later_h_api_version`)
}

launchBgTask <- function(secsToSleep) {
	invisible(.Call(`_latertest_launchBgTask`, secsToSleep))
}

checkLaterOrdering <- function() {
	invisible(.Call(`_latertest_checkLaterOrdering`))
}

cpp_error <- function(value) {
	invisible(.Call(`_latertest_cpp_error`, value))
}

asyncFib <- function(resolve, reject, x) {
	invisible(.Call(`_latertest_asyncFib`, resolve, reject, x))
}

testfd <- function() {
	.Call(`_latertest_testfd`)
}
