// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// callback_registry.cpp
void testCallbackOrdering();
extern "C" SEXP _later_testCallbackOrdering() {
  BEGIN_CPP4R
    testCallbackOrdering();
    return R_NilValue;
  END_CPP4R
}
// debug.cpp
std::string log_level(std::string level);
extern "C" SEXP _later_log_level(SEXP level) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(log_level(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(level)));
  END_CPP4R
}
// debug.cpp
bool using_ubsan();
extern "C" SEXP _later_using_ubsan() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(using_ubsan());
  END_CPP4R
}
// fd.cpp
SEXP execLater_fd(SEXP callback, cpp4r::integers readfds, cpp4r::integers writefds, cpp4r::integers exceptfds, SEXP timeoutSecs, cpp4r::integers loop_id);
extern "C" SEXP _later_execLater_fd(SEXP callback, SEXP readfds, SEXP writefds, SEXP exceptfds, SEXP timeoutSecs, SEXP loop_id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(execLater_fd(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(callback), cpp4r::as_cpp<cpp4r::decay_t<cpp4r::integers>>(readfds), cpp4r::as_cpp<cpp4r::decay_t<cpp4r::integers>>(writefds), cpp4r::as_cpp<cpp4r::decay_t<cpp4r::integers>>(exceptfds), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(timeoutSecs), cpp4r::as_cpp<cpp4r::decay_t<cpp4r::integers>>(loop_id)));
  END_CPP4R
}
// fd.cpp
bool fd_cancel(SEXP xptr);
extern "C" SEXP _later_fd_cancel(SEXP xptr) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(fd_cancel(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(xptr)));
  END_CPP4R
}
// later.cpp
void setCurrentRegistryId(int id);
extern "C" SEXP _later_setCurrentRegistryId(SEXP id) {
  BEGIN_CPP4R
    setCurrentRegistryId(cpp4r::as_cpp<cpp4r::decay_t<int>>(id));
    return R_NilValue;
  END_CPP4R
}
// later.cpp
int getCurrentRegistryId();
extern "C" SEXP _later_getCurrentRegistryId() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(getCurrentRegistryId());
  END_CPP4R
}
// later.cpp
bool deleteCallbackRegistry(int loop_id);
extern "C" SEXP _later_deleteCallbackRegistry(SEXP loop_id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(deleteCallbackRegistry(cpp4r::as_cpp<cpp4r::decay_t<int>>(loop_id)));
  END_CPP4R
}
// later.cpp
bool notifyRRefDeleted(int loop_id);
extern "C" SEXP _later_notifyRRefDeleted(SEXP loop_id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(notifyRRefDeleted(cpp4r::as_cpp<cpp4r::decay_t<int>>(loop_id)));
  END_CPP4R
}
// later.cpp
void createCallbackRegistry(int id, int parent_id);
extern "C" SEXP _later_createCallbackRegistry(SEXP id, SEXP parent_id) {
  BEGIN_CPP4R
    createCallbackRegistry(cpp4r::as_cpp<cpp4r::decay_t<int>>(id), cpp4r::as_cpp<cpp4r::decay_t<int>>(parent_id));
    return R_NilValue;
  END_CPP4R
}
// later.cpp
bool existsCallbackRegistry(int id);
extern "C" SEXP _later_existsCallbackRegistry(SEXP id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(existsCallbackRegistry(cpp4r::as_cpp<cpp4r::decay_t<int>>(id)));
  END_CPP4R
}
// later.cpp
cpp4r::sexp list_queue_(int id);
extern "C" SEXP _later_list_queue_(SEXP id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(list_queue_(cpp4r::as_cpp<cpp4r::decay_t<int>>(id)));
  END_CPP4R
}
// later.cpp
bool execCallbacks(double timeoutSecs, bool runAll, int loop_id);
extern "C" SEXP _later_execCallbacks(SEXP timeoutSecs, SEXP runAll, SEXP loop_id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(execCallbacks(cpp4r::as_cpp<cpp4r::decay_t<double>>(timeoutSecs), cpp4r::as_cpp<cpp4r::decay_t<bool>>(runAll), cpp4r::as_cpp<cpp4r::decay_t<int>>(loop_id)));
  END_CPP4R
}
// later.cpp
bool idle(int loop_id);
extern "C" SEXP _later_idle(SEXP loop_id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(idle(cpp4r::as_cpp<cpp4r::decay_t<int>>(loop_id)));
  END_CPP4R
}
// later.cpp
void ensureInitialized();
extern "C" SEXP _later_ensureInitialized() {
  BEGIN_CPP4R
    ensureInitialized();
    return R_NilValue;
  END_CPP4R
}
// later.cpp
std::string execLater(SEXP callback, double delaySecs, int loop_id);
extern "C" SEXP _later_execLater(SEXP callback, SEXP delaySecs, SEXP loop_id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(execLater(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(callback), cpp4r::as_cpp<cpp4r::decay_t<double>>(delaySecs), cpp4r::as_cpp<cpp4r::decay_t<int>>(loop_id)));
  END_CPP4R
}
// later.cpp
bool cancel(std::string callback_id_s, int loop_id);
extern "C" SEXP _later_cancel(SEXP callback_id_s, SEXP loop_id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cancel(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(callback_id_s), cpp4r::as_cpp<cpp4r::decay_t<int>>(loop_id)));
  END_CPP4R
}
// later.cpp
double nextOpSecs(int loop_id);
extern "C" SEXP _later_nextOpSecs(SEXP loop_id) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(nextOpSecs(cpp4r::as_cpp<cpp4r::decay_t<int>>(loop_id)));
  END_CPP4R
}

extern "C" {
/* .Call calls */
extern SEXP _later_new_weakref(SEXP);
extern SEXP _later_wref_key(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_later_cancel",                 (DL_FUNC) &_later_cancel,                 2},
    {"_later_createCallbackRegistry", (DL_FUNC) &_later_createCallbackRegistry, 2},
    {"_later_deleteCallbackRegistry", (DL_FUNC) &_later_deleteCallbackRegistry, 1},
    {"_later_ensureInitialized",      (DL_FUNC) &_later_ensureInitialized,      0},
    {"_later_execCallbacks",          (DL_FUNC) &_later_execCallbacks,          3},
    {"_later_execLater",              (DL_FUNC) &_later_execLater,              3},
    {"_later_execLater_fd",           (DL_FUNC) &_later_execLater_fd,           6},
    {"_later_existsCallbackRegistry", (DL_FUNC) &_later_existsCallbackRegistry, 1},
    {"_later_fd_cancel",              (DL_FUNC) &_later_fd_cancel,              1},
    {"_later_getCurrentRegistryId",   (DL_FUNC) &_later_getCurrentRegistryId,   0},
    {"_later_idle",                   (DL_FUNC) &_later_idle,                   1},
    {"_later_list_queue_",            (DL_FUNC) &_later_list_queue_,            1},
    {"_later_log_level",              (DL_FUNC) &_later_log_level,              1},
    {"_later_new_weakref",            (DL_FUNC) &_later_new_weakref,            1},
    {"_later_nextOpSecs",             (DL_FUNC) &_later_nextOpSecs,             1},
    {"_later_notifyRRefDeleted",      (DL_FUNC) &_later_notifyRRefDeleted,      1},
    {"_later_setCurrentRegistryId",   (DL_FUNC) &_later_setCurrentRegistryId,   1},
    {"_later_testCallbackOrdering",   (DL_FUNC) &_later_testCallbackOrdering,   0},
    {"_later_using_ubsan",            (DL_FUNC) &_later_using_ubsan,            0},
    {"_later_wref_key",               (DL_FUNC) &_later_wref_key,               1},
    {NULL, NULL, 0}
};
}

void later_init(DllInfo * dll);

extern "C" attribute_visible void R_init_later(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  later_init(dll);
  R_forceSymbols(dll, TRUE);
}
