# Generated by cpp4r: do not edit by hand

#' @title Testing Function
#' @rdname testing
#' @export
later2_dll_api_version <- function() {
	.Call(`_later2test_later2_dll_api_version`)
}

#' @title Testing Function
#' @rdname testing
#' @export
later2_h_api_version <- function() {
	.Call(`_later2test_later2_h_api_version`)
}

#' @title Testing Function
#' @rdname testing
#' @param secsToSleep seconds to sleep (integer)
#' @export
launchBgTask <- function(secsToSleep) {
	invisible(.Call(`_later2test_launchBgTask`, secsToSleep))
}

#' @title Testing Function
#' @rdname testing
#' @export
checkLaterOrdering <- function() {
	invisible(.Call(`_later2test_checkLaterOrdering`))
}

#' @title Testing Function
#' @rdname testing
#' @param value integer value
#' @export
cpp_error <- function(value) {
	invisible(.Call(`_later2test_cpp_error`, value))
}

#' @title Testing Function
#' @rdname testing
#' @param resolve object to resolve (sexp)
#' @param reject object to reject (sexp)
#' @param x value for Fibonnacci task (double)
#' @export
asyncFib <- function(resolve, reject, x) {
	invisible(.Call(`_later2test_asyncFib`, resolve, reject, x))
}

#' @title Testing Function
#' @rdname testing
#' @export
testfd <- function() {
	.Call(`_later2test_testfd`)
}
